spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/TestHR
    username: postgres
    password: 123
  flyway:
    baseline-on-migrate: true

