DROP SEQUENCE IF EXISTS role_seq;
CREATE SEQUENCE role_seq START WITH 1 INCREMENT BY 1;
DROP TABLE IF EXISTS roles CASCADE;
CREATE TABLE roles
(
    id BIGINT NOT NULL,
    name VARCHAR(255),
    PRIMARY KEY (id)
);